version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: datagroup-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dataverse
      - MONGO_INITDB_ROOT_PASSWORD=dataverse
    image: mongo